export enum ACTION_TYPE {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  SELECT = 'SELECT',
  DELETE = 'DELETE',
  RESTORE = 'RESTORE',
  DIMENSION_UPDATE = 'DIMENSION_UPDATE',
  SESSION_USER_LIST_UPDATE = 'SESSION_USER_LIST_UPDATE'
}
