export enum LINE_HEAD {
  NONE = 'NONE',
  ARROW = 'ARROW',
  TRI_ARROW_FILLED = 'TRI_ARROW_FILLED',
  TRI_ARROW_EMPTY = 'TRI_ARROW_EMPTY',
  RHOMBUS_FILLED = 'RHOMBUS_FILLED',
  RHOMBUS_EMPTY = 'RHOMBUS_EMPTY',
}
