export enum ICON {
  PLACEHOLDER = 'PLACEHOLDER',
  PROJECT = 'PROJECT', DIAGRAM = 'DIAGRAM', FOLDER = 'FOLDER', FOLDER_SHARED = 'FOLDER_SHARED',
  PROJECT_FOLDER = "PROJECT_FOLDER",
  PROJECT_CLASS = "PROJECT_CLASS"
}
